name: Install Symphony on Remote VM
on:
  workflow_dispatch:
jobs:
  install_symphony:
    name: Symphony Install via SSH
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and install Symphony
        uses: actions/checkout@v4
        with:
          script: |
            # Install dependencies
            sudo apt update -y
            sudo apt install golang-go -y
            # Install Rust (non-interactive)
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            source $HOME/.cargo/env
            # Clone Symphony repository
            git clone https://github.com/eclipse-symphony/symphony.git
            # Build native Rust library
            cd ~/symphony/api/pkg/apis/v1alpha1/providers/target/rust
            cargo build --release
            # Set library path so Go can link against Rust lib
            export LD_LIBRARY_PATH=$(pwd)/target/release
            cd ~/symphony/api
            # Build symphony-api Go binary
            go build -o symphony-api
            # Run symphony-api
            SYMPHONY_API_URL="http://localhost:8082/v1alpha2/" USE_SERVICE_ACCOUNT_TOKENS="false" ./symphony-api -c ./symphony-api-no-k8s.json -l Debug
