name: Run Symphony Application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Clone Symphony repo
        shell: bash
        run: |
          set -e
          git clone https://github.com/eclipse-symphony/symphony.git $HOME/symphony

      - name: Inspect repo structure
        shell: bash
        run: |
          echo "Directory structure of symphony repo:"
          ls -laR $HOME/symphony

      - name: Build Rust Library
        shell: bash
        run: |
          set -e
          RUST_DIR="$HOME/symphony/api/pkg/apis/v1alpha1/providers/target/rust"
          if [ -d "$RUST_DIR" ]; then
            echo "Rust directory found. Building Rust library..."
            cd "$RUST_DIR"
            cargo build --release
          else
            echo "Rust directory not found. Skipping Rust build."
          fi

      - name: Build Go binary
        shell: bash
        run: |
          set -e
          GO_DIR="$HOME/symphony/api"
          if [ -d "$GO_DIR" ]; then
            echo "Go directory found. Building Go binary..."
            export LD_LIBRARY_PATH=$HOME/symphony/api/pkg/apis/v1alpha1/providers/target/rust/target/release
            cd "$GO_DIR"
            go build -o symphony-api
          else
            echo "Go directory not found. Skipping Go build."
          fi

      - name: Run symphony-api
        shell: bash
        run: |
          set -e
          API_BIN="$HOME/symphony/api/symphony-api"
          if [ -f "$API_BIN" ]; then
            echo "Starting symphony-api in background..."
            cd $HOME/symphony/api
            nohup env SYMPHONY_API_URL="http://localhost:8082/v1alpha2/" USE_SERVICE_ACCOUNT_TOKENS="false" \
              ./symphony-api -c ./symphony-api-no-k8s.json -l Debug > symphony-api.log 2>&1 &
            echo "symphony-api started."
          else
            echo "symphony-api binary not found. Skipping startup."
          fi
          
      - name: Wait for log file
        shell: bash
        run: |
          until [ -f api/symphony-api.log ]; do sleep 1; done
      
      - name: Check for log file
        shell: bash
        run: |
          if [ -f api/symphony-api.log ]; then
            echo "Log file exists"
          else
            echo "Log file missing!"
            ls -R .
          fi
      
      - name: Upload symphony-api log
        uses: actions/upload-artifact@v4
        with:
          name: symphony-api-log
          path: api/symphony-api.log
          if-no-files-found: error
      
