name: Deploy Harbor on GitHub Runner

on:
  push:
    branches:
      - main

jobs:
  deploy-harbor:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo systemctl start docker
        sudo systemctl enable docker
        # Add current user to docker group for docker command without sudo
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Download Harbor Offline Installer
      run: |
        HARBOR_VERSION=2.8.1
        wget https://github.com/goharbor/harbor/releases/download/v${HARBOR_VERSION}/harbor-offline-installer-${HARBOR_VERSION}.tgz
        tar xvf harbor-offline-installer-${HARBOR_VERSION}.tgz
        cd harbor

        # Copy template and configure minimal harbor.yml
        cp harbor.yml.tmpl harbor.yml
        sed -i "s/^hostname: .*/hostname: localhost/" harbor.yml
        sed -i "s/^harbor_admin_password: .*/harbor_admin_password: Harbor12345/" harbor.yml
        sed -i "s/^# http:/http:/; s/^#   port: 80/  port: 80/" harbor.yml
        sed -i "s/^# https:/# https:/" harbor.yml

        # Install Harbor with docker-compose
        ./install.sh --with-docker-compose

        # Start Harbor services
        docker-compose up -d

    - name: Check Harbor status
      run: docker ps -a
