name: Install Gogs on GitHub Runner

on:
  workflow_dispatch:

jobs:
  install-gogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker & Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose
          sudo systemctl start docker
          sudo usermod -aG docker $USER
          newgrp docker

      - name: Run Gogs install script
        run: |
          chmod +x ./install_gogs.sh
          ./install_gogs.sh

      - name: Verify containers
        run: docker ps -a
