name: Install Gogs on GitHub Runner

on:
  workflow_dispatch:

jobs:
  install-gogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker & Docker Compose
        run: |
              sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose       
              docker version
              docker-compose version

      - name: Run Gogs install script
        run: |
          chmod +x ./install_gogs.sh
          ./install_gogs.sh

      - name: Verify containers
        run: docker ps -a
