name: Manual Run Workflow

on:
  workflow_dispatch:  # Enables manual trigger from the GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
